package com.sms.genericutility.Enums;

public enum PropertyKey {

	URL,ADMIN_UN,ADMIN_PWD,TEACHER_UN,TEACHER_PWD,GUARDIAN_UN,GUARDIAN_PWD,TIMEOUTS,BROWSER,
	EXTENTREPORT_TITLE,EXTENTREPORT_NAME,EXTENTREPORT_BROWSER,OVERRIDEREPORT
}
